### ISSUE TITLE
context in the synthetic nn, is it different from the paper?

### ISSUE THREAD

**Issue by slowbull** [koz4k/dni-pytorch#1]
In your code, the context(label) is input to a linear model, https://github.com/koz4k/dni-pytorch/blob/b14a07cab049a72c104b57dcdb56730ab8dbafb1/examples/mnist-cnn/main.py#L106, in the paper, it says that "For convolutional networks we add label information in the form of one-hot encoded channel masks, thus we simply concatenate ten additional channels to the activations, nine out of which are filled with zeros, and one (corresponding to sample’s label) is filled with ones". 

why do you implement like this?

**Comment by koz4k** [comment]
I implemented it like this for simplicity. It should work the same - otherwise we would be doing a convolution over a feature map that is constant everywhere (in the spatial dimensions), which is equivalent to taking a single linear projection and then expanding the output to the appropriate shape.

The only difference can be in weight initialization, as the number of inputs is different, but it shouldn't matter much as it's just scaling by a constant factor.

**Comment by slowbull** [comment]
Thanks for your response. One more question, if I want to split a network into more parts, not just two, is it correct to just add more backward_interfaces in the forward() of Net()? anything should I take care?

**Comment by koz4k** [comment]
It should work fine with any number of parts, as you described. However if you share parameters between those parts, you'll need to use `defer_backward`.

**Comment by slowbull** [comment]
Thanks.
